x-worker-common: &worker-common
  build: .
  restart: unless-stopped
  env_file: .env
  depends_on:
    nvpn-redis:
      condition: service_healthy
  entrypoint: ['node']

services:
  nvpn-redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  nvpn-comment-service:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      nvpn-redis:
        condition: service_healthy

  worker-parser:
    <<: *worker-common
    command: ['dist/workers/parser.worker.js']

  worker-sender:
    <<: *worker-common
    command: ['dist/workers/sender.worker.js']

  worker-retry:
    <<: *worker-common
    command: ['dist/workers/retry.worker.js']

  worker-status:
    <<: *worker-common
    command: ['dist/workers/status.worker.js']

